version: "3.8"
services:
  gopplista:
    restart: always
    image: ghcr.io/drakejacob/gopplista:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gopplista.rule=Host(`gopplista.drake.ee`)"
      - "traefik.http.services.gopplista.loadbalancer.server.port=3333"
      - "traefik.http.routers.gopplista.entrypoints=websecure"
      - "traefik.http.routers.gopplista.tls.certresolver=myresolver"
    # env:
      # - ADMIN_PASSWORD=<password> # will be set directly in portainer
      # - SEED_DATABASE=true 
      # - ENV=dev
    env_file:
      - stack.env
    volumes:
      - gopplista-db:/app/sqlite

volumes:
  gopplista-db:
