// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import ()

type Game struct {
	ID          string
	Title       string
	Description string
	Genre       string
	ReleaseYear int64
	Rating      int64
	ImageUrl    string
}

type GameSection struct {
	ID          string
	Title       string
	Description string
	OrderOnPage int64
}

type GameSectionGame struct {
	GameSectionID  string
	GameID         string
	OrderInSection int64
}
